apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
    component: datanode
  name: datanode-svc
spec:
  ports:
    - name: "8999"
      port: 8999
      targetPort: 8999
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    app: graylog
    component: datanode