apiVersion: v1
kind: Service
metadata:
  name: graylog-svc
  labels:
    app: graylog
    component: graylog-web
spec:
  type: NodePort
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
    - name: "5140"
      port: 5140
      protocol: UDP
      targetPort: 5140
    - name: 5140-tcp
      port: 5140
      targetPort: 5140
    - name: "5555"
      port: 5555
      targetPort: 5555
    - name: 5555-udp
      port: 5555
      protocol: UDP
      targetPort: 5555
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: {{ .Values.service.nodePort }}
    - name: "12201"
      port: 12201
      targetPort: 12201
    - name: 12201-udp
      port: 12201
      protocol: UDP
      targetPort: 12201
    - name: "13301"
      port: 13301
      targetPort: 13301
    - name: "13302"
      port: 13302
      targetPort: 13302
  selector:
    app: graylog
    component: graylog-web